version: "3.8"
services:
  mysql_db:
    image: mysql:8.0.23
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: "contacts"
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_ROOT_HOST: "%"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -pexample"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  contacts-backend:
    build: ./contacts-backend
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - 3000:3000
    working_dir: /usr/src/app
  web-client:
    build: ./contacts-web-client
    ports:
      - 80:80
